name: Website Update

on: pull_request

jobs:
  generate_website:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          clean: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements_web.txt

      - name: Generate website
        run: python3 website-generator/generator.py --config ./setup/config.json

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |
                ${{ secrets.public_deploy_key }}

      - name: Git setup
        run: . setup/git-setup.sh

#       - name: Deploy website
#         run: . setup/git-deploy-website.sh
